### ISSUE TITLE
Duplicate file when bundling for Android

### ISSUE THREAD

**Issue by passy** [phax/ph-css#10]
Apologies for the poor bug report, but I'm hoping that this might ring a bell regardless.

I've been trying to include your library (4.0.0) in an Android project, but upon compiling I get this error:

```
Error:Gradle: Execution failed for task ':app:packageDebug'.
> Duplicate files copied in APK META-INF/buildinfo.xml
  	File 1: /home/pascal/.gradle/caches/modules-2/files-2.1/com.helger/ph-commons/6.1.0/7f96428cbbf7e4c88e9663d09070f24792321254/ph-commons-6.1.0.jar
  	File 2: /home/pascal/.gradle/caches/modules-2/files-2.1/com.helger/ph-css/4.0.0/3a0ce4d7bcd6eb6a162c3d8336fb70d2c0e4a4fa/ph-css-4.0.0.jar
```

Unfortunately I have no idea what the `buildinfo.xml` is for and why this would be a problem. Have you seen this before? Is this expected? Is the Android build system just broken?

Thank you!

**Comment by phax** [comment]
This is no stupid question at all.
These files contain information about the host where the application was build and they are created by my https://github.com/phax/ph-buildinfo-maven-plugin

Anyway they are not mission critical, so you can do the following things without getting into problems: delete, move, merge, rename - do whatever you like with them!

I don't know Gradle so you have to find the technical solution yourself :)

**Comment by passy** [comment]
Thanks for your reply! Embarrassingly enough, this appears to have been a temporary issue (damn you, global mutable state). Both on CI and my second computer it seems to work just fine. So I'll just clean my caches when I'm back home, but this is definitely not an issue related to your libraries.

Thanks again and sorry for the noise!

**Comment by phax** [comment]
No problem - glad it works :)

**Comment by adam1929** [comment]
For Android builds -> add this to app/build.gradle:
```
android {
packagingOptions {
        exclude("META-INF/buildinfo.xml")
    }
}
```

**Comment by phax** [comment]
@adam1929  interesting - why does it cause problems?
