### ISSUE TITLE
ph-css parser cannot parse pseudo class containing attribute selector

### ISSUE THREAD

**Issue by subbudvk** [phax/ph-css#101]
I tried parsing has() pseudo class containing attribute selector which failed.

Like has(name='a') {} which is valid. But looks like has() isnt supported at all, and this combination issue could exist for existing supported pseudo classes

**Comment by subbudvk** [comment]
@phax

**Comment by phax** [comment]
The main issue here, are the relative selectors that are currently not supported: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_selectors/Selector_structure#relative_selector

**Comment by subbudvk** [comment]
Figured out, thanks

**Comment by phax** [comment]
So fixing this one together with #88 - sorry for the delay. Will be part of the 7.0.3 release
