### ISSUE TITLE
Parsing inline style

### ISSUE THREAD

**Issue by subbudvk** [phax/ph-css#103]
While currently it is supposed to parse internal css in `<style></style>` it is useful to provide parsing options for inline styles like 
```
<p style="">test</p>
```

Changes wise it might simply be considering them as declarations if i am not missing something

**Comment by phax** [comment]
Hi @subbudvk ,
This can already be done today.
Simply use class `CSSReaderDeclarationList` instead of `CSSReader` to read the `style` attribute

**Comment by subbudvk** [comment]
Thanks
