### ISSUE TITLE
CssReader#getCharsetDeclaredInCSS(IHasInputStream) closes InputStream

### ISSUE THREAD

**Issue by johannburkard** [phax/ph-css#12]
In ``CssReader#readFromStream(IHasInputStream, CSSReaderSettings)``, you call ``CssReader#getCharsetDeclaredInCSS(IHasInputStream)`` which closes the ``InputStream`` as a side-effect.

Once the input stream is closed, parsing it is less likely to work.

**Comment by phax** [comment]
This is "works as designed". As the JavaDoc for aISP notes, the input stream must be openable for multiple times (as least this is what I would indicate). I suggest you have a look at `ClassPathResource` or  `FileSystemResource` for an easy to use of `IHasInputStream`.

**Comment by phax** [comment]
Does that solve your issue???
