### ISSUE TITLE
support -ms-high-contrast as a media express

### ISSUE THREAD

**Issue by david-truong** [phax/ph-css#15]
It's often used to do media queries for IE specific browsers/versions

https://jeffclayton.wordpress.com/2014/07/22/internet-explorer-css-hacks-collection/

**Comment by phax** [comment]
I think you are referring to the warning 
```
Media expression uses unknown feature '-ms-high-contrast'
```
Anyway this is just a warning, and the feature is read (and stored and written) anyway.
It's just a warning about a non-standard feature :)
