### ISSUE TITLE
What's the License of the project

### ISSUE THREAD

**Issue by pmouawad** [phax/ph-css#16]
Hello,
Nice library idea, it's missing.
Under what license is it delivered ?
Ideally , an Apache 2.0 license would be great, but I don't see any LICENSE file.
Thanks

**Comment by pmouawad** [comment]
Ok , I found the license and it's Apache :-)
https://github.com/phax/ph-css/blob/master/src/main/resources/LICENSE
Maybe it should be at root so that it's immediately visible.

**Comment by phax** [comment]
It's also stated directly on the start page https://github.com/phax/ph-css as a separate paragraph :)
