### ISSUE TITLE
java.lang.NullPointerException: The value of 'CSS' may not be null!

### ISSUE THREAD

**Issue by pmouawad** [phax/ph-css#17]
Parsing a particular CSS, I get :

java.lang.NullPointerException: The value of 'CSS' may not be null!
	at com.helger.commons.ValueEnforcer.notNull(ValueEnforcer.java:86)
	at com.helger.css.decl.visit.CSSVisitor.visitCSS(CSSVisitor.java:378)
	at com.helger.css.decl.visit.CSSVisitor.visitCSSUrl(CSSVisitor.java:416)
	at TestCSS.readFromStyleAttributeWithAPI(TestCSS.java:68)
	at TestCSS.main(TestCSS.java:44)

I use attached code
[TestCSS.java.zip](https://github.com/phax/ph-css/files/190222/TestCSS.java.zip)
Attached css file:
[test.css.zip](https://github.com/phax/ph-css/files/190220/test.css.zip)

Thanks

**Comment by phax** [comment]
I'm on vacation. Will look at it when I'm back

**Comment by pmouawad** [comment]
Thanks for answer.
After further investigation, issue is that :

```
final CascadingStyleSheet aCSS = CSSReader.readFromString(
                    cssContent, 
                    Charset.forName(encoding),
                    ECSSVersion.CSS30,
                    new LoggingCSSParseErrorHandler(),
                    new LoggingCSSParseExceptionCallback()
                    );
```
returns null.
Validating CSS against https://jigsaw.w3.org/css-validator, it has certainly errors, but should method return null ?

**Comment by pmouawad** [comment]
After even more investigation :-) , It appears I am facing unrecoverable error in css so it is supposed to be OK.
But if CSS3 is lax (as per your answer in other issue), should we face an unrecoverable exception if browser doesn't ?

Thanks

**Comment by phax** [comment]
There is a so called 'browser compliant mode' that can be enabled in the Settings of the reader. Try this one.
With lax ai thought you mean 'version lax' ;)

Am 28. März 2016 03:00:08 GMT+13:00, schrieb Philippe M <notifications@github.com>:
>After even more investigation :-) , It appears I am facing
>unrecoverable error in css so it is supposed to be OK.
>But if CSS3 is lax (as per your answer in other issue), should we face
>an unrecoverable exception if browser doesn't ?
>
>Thanks
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/phax/ph-css/issues/17#issuecomment-202068639

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by pmouawad** [comment]
Hello,
I tried it, it doesn't change behaviour.
The parse failing errors I have are:
`@ -moz-document url-prefix(){`
Exception:
`error:http://www.bricodepot.fr/docroot/css/web.css?v=4.6.0 code:Non HTTP response code: org.apache.jmeter.protocol.http.parser.LinkExtractorParseException message:Non HTTP response message: java.lang.IllegalStateException: Failed to parse CSS: http://www.bricodepot.fr/docroot/css/web.css?v=4.6.0, [468:1] Encountered text '@' corresponding to token <UNKNOWN>. Was expecting one of: <EOF>, <S>, "}", "[", ".", ":", "*", "|", <HASH>, "", "@charset", "@import", "@namespace", "@page", "@top-left-corner", "@top-left", "@top-center", "@top-right", "@top-right-corner", "@bottom-left-corner", "@bottom-left", "@bottom-center", "@bottom-right", "@bottom-right-corner", "@left-top", "@left-middle", "@left-bottom", "@right-top", "@right-middle", "@right-bottom", "@media", "@font-face", <KEYFRAMES_SYM>, <VIEWPORT_SYM>, "@supports", <AT_UNKNOWN>, <IDENT>, <PERCENTAGE>, ":not(", 

Response header`

Second failure:
`@ -webkit-keyframes buffering-stripes{from{background-position:0 0}to{background-position:30px 0}`

Error:
`291:1] Encountered text '@' corresponding to token <UNKNOWN>. Was expecting one of: <EOF>, <S>, "}", "[", ".", ":", "*", "|", <HASH>, "<!--", "-->", "@charset", "@import", "@namespace", "@page", "@top-left-corner", "@top-left", "@top-center", "@top-right", "@top-right-corner", "@bottom-left-corner", "@bottom-left", "@bottom-center", "@bottom-right", "@bottom-right-corner", "@left-top", "@left-middle", "@left-bottom", "@right-top", "@right-middle", "@right-bottom", "@media", "@font-face", <KEYFRAMES_SYM>, <VIEWPORT_SYM>, "@supports", <AT_UNKNOWN>, <IDENT>, <PERCENTAGE>, ":not(", `

Third code:
`.userActionsArea>ul>li:first-child a,.userActionsArea>ul>li:first-child span>{border-left:1px solid #fff}`
Error:
`[54:77] Encountered text '>' corresponding to token ">". Was expecting one of: <S>, <LBRACE>, "[", ".", <COMMA>, ":", <HASH>, ":not(", <HASH>, ".", "[", ":", ":not(", ":not(", ":not(", ":not(", ":not(", ":not(", ":not(", ":not(", ":not(", <HASH>, ".", "[", ":", ":not(", <S>, <S>, `


4th code :
`.filter h2{padding:0 0 20px 0}.--line .carousel{background:#eaeaea}.btn_rt{background:url(/crsdocroot/images/EPAM-box-img/sprite.png) no-repeat 0 -183px}`
Error:
`17:32] Encountered text '-' corresponding to token "-". Was expecting one of: "inherit", "and", "not", "only", "from", "to", "or", <IDENT>
	at org.apache.jmeter.protocol.http.parser.CssParser.getEmbeddedResourceURLs(CssParser.java:135)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.downloadPageResources(HTTPSamplerBase.java:1198)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.resultProcessing(HTTPSamplerBase.java:1625)
	at org.apache.jmeter.protocol.http.sampler.HTTPAbstractImpl.resultProcessing(HTTPAbstractImpl.java:463)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.sample(HTTPHC4Impl.java:406)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerProxy.sample(HTTPSamplerProxy.java:74)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase$ASyncSample.call(HTTPSamplerBase.java:1958)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase$ASyncSample.call(HTTPSamplerBase.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by phax** [comment]
Issues 1 and 2 are solved in trunk by making `@` alone force the parser to jump in "unknown rule" mode.

**Comment by phax** [comment]
Issue 4 is also solved - explicitly allowing for "--" as a prefix. See http://stackoverflow.com/questions/30819462/can-css-identifiers-begin-with-two-hyphens for details :)

**Comment by phax** [comment]
Issue 3 is a bit more complex. Do you know what browsers do with invalid selectors?
Are they using the first valid selectors, or do they skip the rules as a whole?

**Comment by phax** [comment]
Locally things are working for issue 3. Please check with the latest SNAPSHOT

**Comment by pmouawad** [comment]
Hi @phax ,
Is this fix in the release version that you mention in another issue ?

Thanks

**Comment by phax** [comment]
Yes, in 4.1.1 - all 4 issues will work when selecting browser compliant mode
