### ISSUE TITLE
Is there a Lax Parser ?

### ISSUE THREAD

**Issue by pmouawad** [phax/ph-css#18]
Hello,
Currently, my understanding of parsing is that you have to set a CSS version.
Is there a Relax parser that is able to understand different versions ?
In fact I am only interested in parsing URLs, I used com.helger.css.decl.visit.DefaultCSSUrlVisitor and the sample code referenced in your documentation.
Thanks

**Comment by phax** [comment]
Use the 3.0 version parser. It can read basically evetything :)

**Comment by phax** [comment]
I think this is related to issue #17. There is no real "lax" parser that eats everything. Certain specific errors are explicitly handled (e.g. errors in style declarations - as in `color:red`) but currently the selector handling is not very "lax". So if an invalid selector is present it breaks with an unrecoverable error. See also issue #19 - lets resolve these errors and I assume it will do the trick for you - okay?

**Comment by pmouawad** [comment]
Hi @phax ,
Yes it will do what I need.
Thanks for your work and efforts

**Comment by phax** [comment]
Version 4.1.1 is on its way to Maven Central
