### ISSUE TITLE
Another parsing exception in browser-compliant mode

### ISSUE THREAD

**Issue by givankin** [phax/ph-css#21]
Hey Philip, hope you're doing well.

We have another non-recoverable CSS exception found in the wild, so this is similar to #19.

The CSS that is causing the failure is
```
//...
}

;
:root .cw18winwrap {
//...
```

- the semicolon in selector is the bad guy.

fyi, the CSS is found on http://www.oracle.com/technetwork/java/javase/downloads/index.html web page. And it has a bunch of other errors (as validated by csslint.net) which don't cause failures, so current state of the parser is already much closer to what browsers have in terms of error-handling.

**Comment by phax** [comment]
4.1.2 is on its way to Maven central. Enjoy.
