### ISSUE TITLE
Parsing of reduced calc rules fails

### ISSUE THREAD

**Issue by Artur-** [phax/ph-css#25]
See http://cssnext.io/features/#reduced-calc

`font-size: calc(var(--fontSize) * 2)` cannot be parsed

**Comment by phax** [comment]
Hi! Can you please point me to the official W3 spec for reduced calc - thanks

**Comment by phax** [comment]
Media query ranges and nested selectors also don't work (and maybe other stuff as well - will investigate further)

**Comment by Artur-** [comment]
https://www.w3.org/TR/css-variables/ mentions at least a few calc examples, e.g.
```
.foo {
  --gap: 20;
  margin-top: calc(var(--gap) * 1px);
}
```

**Comment by phax** [comment]
It's working now in HEAD version. Does that fit your needs? The JDK8 version will be released soon

**Comment by Artur-** [comment]
Awesome work! JDK8 and "soon" is good enough for my needs 👍

**Comment by phax** [comment]
Version for JDK8 is on Maven Central
