### ISSUE TITLE
fontface missing getDeclaration()

### ISSUE THREAD

**Issue by flyboarder** [phax/ph-css#27]
fontface missing getDeclaration(), all the other rules have it.

**Comment by phax** [comment]
The class `FontFaceRule` has a method `getAllDeclarations()` to retrieve all contained declarations

**Comment by flyboarder** [comment]
Shouldn't all the rules have something like:
https://github.com/phax/ph-css/blob/4078abb0cd68104aaf0159df04e42707259a65c4/src/main/java/com/helger/css/decl/CSSViewportRule.java#L67-L77

**Comment by phax** [comment]
Thanks for pointing this out. I additionally extended the grammar to support stuff like "@-moz-font-face". Will be contained in 5.0.1 release

**Comment by flyboarder** [comment]
I also found that calling `getAsCSSString()` on `CSSSelector` returns utf-8 encoded strings, not the actual utf-8 character. ex. `.row.\\32 00\\25` how can I get the correct string?

**Comment by flyboarder** [comment]
@phax I narrowed this down to the `CSSSelectorSimpleMember` class.
