### ISSUE TITLE
Unsupported Class file version 52.0 Android

### ISSUE THREAD

**Issue by EhiltonKazuo** [phax/ph-css#28]
Good afternoon,
Apologies for the poor grammar and supposed bug. I'm newer developer in android studio.
I trying to use your library with gradle/maven and when i run the app this message shows:

```
Error:PARSE ERROR:
Error:unsupported class file version 52.0
Error:...while parsing com/helger/commons/CGlobal.class
Error:1 error; aborting
:app:transformClassesWithDexForDebug FAILED
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_65\bin\java.exe'' finished with non-zero exit value 1
```

I tried to use this post in stackoverflow
**http://stackoverflow.com/questions/37902840/got-unsupported-class-file-version-52-0-after-including-a-module-to-a-project**
Nothing happens...
And when i saw your changelog about jdk 8, i tried to use this instead:
**https://developer.android.com/preview/j8-jack.html?hl=en**
I removed the duplicate files and this message shows:

```
Error:Library reading phase: Type javax.annotation.Untainted from file 'C:\Users\user\AndroidStudioProjects\CSSTest\app\build\intermediates\jill\debug\packaged\jsr305-3.0.1-dd0e9f5d0efb3025f6fde4238fd4a5c268f62a63.jar' has already been imported from file 'C:\Users\user\AndroidStudioProjects\CSSTest\app\build\intermediates\jill\debug\packaged\annotations-3.0.1u2-2b84c751906484cab0381cba276af74c2923d73b.jar', type 'javax.annotation.Untainted' (see property 'jack.import.type.policy' for type collision policy)
com.android.jack.api.v01.CompilationException: Library reading phase: Type javax.annotation.Untainted from file 'C:\Users\user\AndroidStudioProjects\CSSTest\app\build\intermediates\jill\debug\packaged\jsr305-3.0.1-dd0e9f5d0efb3025f6fde4238fd4a5c268f62a63.jar' has already been imported from file 'C:\Users\user\AndroidStudioProjects\CSSTest\app\build\intermediates\jill\debug\packaged\annotations-3.0.1u2-2b84c751906484cab0381cba276af74c2923d73b.jar', type 'javax.annotation.Untainted' (see property 'jack.import.type.policy' for type collision policy)
```

**Comment by phax** [comment]
Hi! I'm not an Android developer, but you may try version 5.0.1-SNAPSHOT, as I recently changed the annotation usage handling in the base class. If necessary I could also create you a 5.0.1 release if absolutely necessary.

**Comment by EhiltonKazuo** [comment]
Thank you, I appreciate it =D

**Comment by phax** [comment]
So is it working? Or are you waiting for me to release 5.0.1?

**Comment by EhiltonKazuo** [comment]
Sorry for late reply, I added your source code in github and attached the dependencies ph-commons in maven repositories, but one import in android doesn't recognized.
`import org.omg.CORBA_2_3.portable.OutputStream;`
in CSSDataURL.java
I will search this later

**Comment by phax** [comment]
Thanks for pointing this out - this is an error :)

**Comment by EhiltonKazuo** [comment]
I forgot to tell you about the links in section "Code Examples". it appears "Page not found".

**Comment by phax** [comment]
Links are fixed. Thanks for pointing this out!

**Comment by phax** [comment]
Version 5.0.1 was released and is on it's way to Maven Central. It fixes the OutputStream issue and should also fix the annotation problem.

**Comment by phax** [comment]
So does 5.0.1 solve your problem?

**Comment by EhiltonKazuo** [comment]
No. I think the problem is the jdk 8, because this feature was created recently.

**Comment by phax** [comment]
Any news on this? Can Android handle JDK 8 JAR files? Otherwise you may use version 4.1.4 - the last one to be compiled against JDK 6.

**Comment by EhiltonKazuo** [comment]
Nobody replied my message in stackoverflow.

Em 12/09/2016 07:00, "Philip Helger" <notifications@github.com> escreveu:

**Comment by phax** [comment]
Checkout the last point of the main answer from http://stackoverflow.com/questions/23318109/is-it-possible-to-use-java-8-for-android-development:

> Now it is possible to use some features of java 8 using the new toolchain called [Jack & Jill](http://tools.android.com/tech-docs/jackandjill), as mentioned in [GOOGLE I/O 2016](https://youtu.be/B08iLAtS3AQ?t=28m14s), but still does not support all java 8 features. For a how-to see [Java 8 Language Features | Android Developers](https://developer.android.com/preview/j8-jack.html).

**Comment by phax** [comment]
I think this is not a real ph-css topic :)
