### ISSUE TITLE
Unclosed CSS rule recovers as soon as non-matching "}" is encountered (and this is not what browsers do)

### ISSUE THREAD

**Issue by abbakym** [phax/ph-css#3]
Imagine we have this piece of CSS:
`.class{color:red;.class{color:green}.class{color:blue}`

After parsing it will become smt. like:
`.class{color:red}.class{color:blue}`
i.e. first closing bracket will be treated as _matched_ and invalid rule content (`.class{color:green`) will be thrown away.

And browsers will throw away everything until the _matching_ closing bracket: in our example it is everything after `red;`. I.e. browser would treat the example like this:
`.class{color:red;}`

Is it possible to tweak parser to behave more like browsers do in such cases? Maybe some configuration options?

Thanks!

**Comment by mskotnikov** [comment]
Hi Philip!
Would it be possible to fix this issue in the nearest major release, e.g. 4.0.0 and document the incompatibility you mentioned?
The issue makes CSS passing through the parser not usable in the browser environment.

**Comment by phax** [comment]
What I could think of is an alternative parser that is not based on a grammar but uses a more fuzzy way (self written lexer and parser). Do you have an idea whether there is a starting point for this?

**Comment by abbakym** [comment]
I know of at least one such parser (it already figured in the comments above): https://github.com/CSSLint/parser-lib. It's author particularly mentions that one of the goal was to match error handling behavior with browsers.

**Comment by phax** [comment]
I started a new try with a special parser flag - I will let you know when there is something to test

**Comment by abbakym** [comment]
Thanks, eager to try! =)

**Comment by phax** [comment]
If you use the trunk you can try. For reading use a CSSReaderSettings Object and use `setBrowserCompliantMode (true)` and give me feedback :)
Currently some tests are still failing but that should not hinder your testing (`-DskipTests=true` on mvn commandline)....

**Comment by phax** [comment]
Okay, please try version 4.0.0

**Comment by abbakym** [comment]
@phax key persons are on vacation now. I hope we can give it a try in August.

**Comment by phax** [comment]
Don"t worry...

**Comment by abbakym** [comment]
@phax Checked today, working as expected. Thank you again for your great work!

**Comment by phax** [comment]
Glad that it works - I assume there will be some minor issues with some special cases. Just open new issues for those.
