### ISSUE TITLE
Missing MediaExpressionFeature for old experimental mozilla feature

### ISSUE THREAD

**Issue by FSchumacher** [phax/ph-css#30]
We have  a [bug report for Apache JMeter](https://bz.apache.org/bugzilla/show_bug.cgi?id=60121),  where a user wants to parse a css file that contains `min--moz-device-pixel-ratio `. That variant seems to be missing in the enum `ECSSMediaExpressionFeature` and as a result his log files are getting flooded with error messages.

It would be nice, if you could add this ancient mozilla feature.

Thanks,
 Felix

**Comment by phax** [comment]
Hi! So I add the one you mentioned and some additional vendor specific ones.
Do you need a 4.1.5 backport release immediately or do you have additional things that will pop up?

**Comment by maarthala** [comment]
Hi Phax. It will be great if we get the fix immediately. Right now I dont see other issue related to this. 
Regards,
Surendra

**Comment by phax** [comment]
Okay, I will create a 4.1.5 release tonight

**Comment by maarthala** [comment]
Hi Phax.. Any update on this release.. Thanks.

**Comment by phax** [comment]
Sorry - forgot about. Mea culpa. Work in progress

**Comment by phax** [comment]
4.1.5 should be Maven Central soon

**Comment by FSchumacher** [comment]
Thanks for your speedy response,
 Felix
