### ISSUE TITLE
Appengine does not yet support java 8

### ISSUE THREAD

**Issue by biancashouse** [phax/ph-css#31]
Philip, my build using ps-css version 5.0.1 cannot be  uploaded to appengine.
For now I am building with 4.1.5.
I don't know if or when Google plan to make java 8 available on appengine, but I'm telling you, because you made a great library, and I imagine there will be many other GAE devs anting to use it.

Thanks

Ian

**Comment by phax** [comment]
Thanks for the information.
Hopefully GAE will support Java 8 soon :)

**Comment by biancashouse** [comment]
I think if I was desperate to start using java 8, I could move from appengine to compute engine, but right now Google suggest it is not ready for production.

**Comment by phax** [comment]
I think this is not a real ph-css topic :)
