### ISSUE TITLE
Not parsing hrefs inside svg tag

### ISSUE THREAD

**Issue by biancashouse** [phax/ph-css#32]
E.g. on the pexels.com website:

     <a class="tiny-profile" data-track-action="home" data-track-label="leaderboard-item" href="/u/ibrahim-asad-45786/"> <img alt="Ibrahim Asad" class="tiny-profile__img" width="30" height="30" src="https://www.gravatar.com/avatar/5fbff6603f724a3b6bfc68b0172ed30b?s=60&amp;d=retro"> <span class="tiny-profile__name">Ibrahim Asad</span> <span class="tiny-profile__downloads"> 
       <svg viewbox="0 0 100 100" class="tiny-profile__downloads-icon">
        <use xlink:href="#iconDownloads"></use>
       </svg> 4.01K </span> </a> 

Chrome shows: Unsafe attempt to load URL http://pexels.com/ from frame with URL http://dev.htmlhub.io:8888/?bookmark-admin=pexels. Domains, protocols and ports must match.

While the above example looks like the href might not actually be a server url, Chrome thinks it is, and anyhow, it didn't get picked up by AbstractModifyingCSSUrlVisitor.

BTW = fantastic library for replacing css embedded urls with data urls. Many thanks. Much appreciated.

Ian

**Comment by phax** [comment]
Hi Ian!
ph-css is currently not crawling any HTML - this is completely out of scope of this library.
So I'm afraid I don't know exactly what you are targeting for.
`AbstractModifyingCSSUrlVisitor` can only be used with CSS content....
Thanks, Philip

**Comment by biancashouse** [comment]
You are right. I think I need to get an early night !
I feel silly now.
