### ISSUE TITLE
Please support IE media type hacks like @media all\0 

### ISSUE THREAD

**Issue by korvindest** [phax/ph-css#33]
Hello Philip.
We found one minor issue in CSS parsing.
Parser doesn't support IE hacks like these
http://keithclark.co.uk/articles/moving-ie-specific-css-into-media-blocks/media-tests/
Could you add support for this one in 4.* thread?
Here is snippet to reproduce the issue.
`        String css = "@media \\0screen\\,screen\\9 {.test {margin-left: 0px}}";
        CSSReaderSettings aSettings = new CSSReaderSettings()
                .setCSSVersion(ECSSVersion.LATEST)
                .setBrowserCompliantMode(true);
        CascadingStyleSheet cascadingStyleSheet = CSSReader.readFromStringStream(css, aSettings);
        CSSWriter writer = new CSSWriter(new CSSWriterSettings(ECSSVersion.LATEST, true));
        System.out.println(writer.getCSSAsString(cascadingStyleSheet));
`

**Comment by phax** [comment]
Hi! I don't see a problem. Is it just about the logged warning
> CSS 3.0 media query uses unknown medium '\0screen\,screen\9 '
??

**Comment by korvindest** [comment]
First of all it is logging. We don't want to filter warnings from your library, because it useful for us. 
I guess, it should stay one media type. Could you implement handling it as known media type?

**Comment by phax** [comment]
What I extend `ICSSParseErrorHandler` to receive some "interpretation issues" via a callback? The default implementation would log them as before. But this would mean an interface incompatibility.

**Comment by phax** [comment]
Well I personally like to now include too many "browser hacks" in the code because I believe that this is bad practice. That's why I included the "browser compliant mode" to explicitly say "I want to handle *bad* CSS as well".
So I will go for the `ICSSParseErrorHandler` extension. You simply pass your implementation to `CSSReaderSettings` and this will handle all other warnings/errors as well.

**Comment by korvindest** [comment]
Ok. I see. Thank you.

**Comment by phax** [comment]
Well I'm not done yet :) I just created the modifications in the head, and will now move it back to the 4.x branch. Stay tuned. Than you can set a special instance of `ICSSInterpretErrorHandler` as shown in https://github.com/phax/ph-css/blob/master/ph-css/src/test/java/com/helger/css/supplementary/issues/Issue33Test.java - ok?

**Comment by phax** [comment]
I will build a release 4.1.6 asap

**Comment by korvindest** [comment]
Oh, I'm sorry. I'm a bit misunderstood you. Test looks OK for me.

**Comment by phax** [comment]
That means: I don't add it to the enum, but you have the possibility to ignore all warnings.

**Comment by phax** [comment]
Versions 4.1.6 and 5.0.2 are on its way to Maven Central. Thanks for the input
