### ISSUE TITLE
Error in handling of empty css block

### ISSUE THREAD

**Issue by korvindest** [phax/ph-css#34]
Hello Philip, there is a one more issue from our QA.
This is example of a bit broken CSS with empty block.
https://jsfiddle.net/b49056u9/3/
As you can see "pen" is blue, because empty block was skipped.

But this code will throw NPE

``` java
String css = ".pen {background-color: red;width:100px; height:100px} {* some incorrect block *} .pen {background-color: blue}";
        CSSReaderSettings aSettings = new CSSReaderSettings()
                .setCSSVersion(ECSSVersion.LATEST)
                .setBrowserCompliantMode(true);
        CascadingStyleSheet cascadingStyleSheet = CSSReader.readFromStringStream(css, aSettings);
        CSSWriter writer = new CSSWriter(new CSSWriterSettings(ECSSVersion.LATEST, true));
        System.out.println(writer.getCSSAsString(cascadingStyleSheet));
```

**Comment by phax** [comment]
The exception is thrown because `cascadingStyleSheet` is `null` because `CSSReader.readFromStringStream` failed

**Comment by givankin** [comment]
@phax just wondering do you have any plans for this one?

**Comment by phax** [comment]
I was playing around with the grammar, but couldn't come up with a working solution :(
I need to investigate further, but currently lacking the time.

**Comment by juanchaur1** [comment]
@phax could you advise us where we could start looking to fix the issue like this?

**Comment by phax** [comment]
Start in file `ph-css\src\main\jjtree\ParserCSS30.jjt` - this contains the grammar.
The first rule is `styleSheet` in line 544.
Use `mvn clean generate-sources` to build chnages on the commandline

**Comment by juanchaur1** [comment]
@phax I've been checking the grammar and in line: 1079 void styleDeclaration() : {}
you change the grammar to:
```
from: PROPERTY COLON S* (EXPR?) IMPORTANT?
to: PROPERTY COLON S* EXPR IMPORTANT?
```
why did you change this?

**Comment by phax** [comment]
The "optional expression" was an IE hack added in the grammar. Nowadays it is preferred to use "Browser Compliant Mode" to handle this kind of errors. So a style declaration always requires a value after the colon (as in `color:red;`). The old style allowed for `color: ;`
