### ISSUE TITLE
did not build

### ISSUE THREAD

**Issue by rolfschumacher** [phax/ph-css#37]
cloned with 
git clone https://github.com/phax/ph-css
did mvn test

on Debian Jessie, openjdk version "1.8.0_102", Apache Maven 3.3.9 
[ph-css.txt](https://github.com/phax/ph-css/files/558425/ph-css.txt)

Then I did a mvn test in ph-css/ph-csscompress-maven-plugin and got errors as well:
[ph-csscompress-maven-plugin.txt](https://github.com/phax/ph-css/files/558429/ph-csscompress-maven-plugin.txt)

My goal is to have a working example for javacc build using maven.

**Comment by phax** [comment]
Weird. It builds with 1.8.0_31 without problems: https://travis-ci.org/phax/ph-css

The error message `Unsupported major.minor version 52.0` indicates that you are not using Java 8

**Comment by rolfschumacher** [comment]
Thank you, that was the right hint:
I upgraded from Java-7 to Java-8. However you got to make sure that not only "java -version" leads to the expected result, but "javac -version" as well. And $JAVA_HOME has to be maintained also. 

If all three point to the same java version, your project runs smooth (with a lot of warnings) applying "mvn test".

**Comment by phax** [comment]
The warnings are okay. They are from the unit tests mostly....
