### ISSUE TITLE
CascadingStyleSheet.getAllStyleRules() does not return rules from @media

### ISSUE THREAD

**Issue by dalibor-drgon** [phax/ph-css#39]
How can I loop through all the style rules including those from `@media` ?

**Comment by phax** [comment]
First say `getAllMediaRules ()` and than, for each `CSSMediaRule` instance call `getAllRules ()`. hth

**Comment by dalibor-drgon** [comment]
Oh thanks. The fact that getAllMediaRules().getAllRules() returns colletion of ICSSTopLevelRule instead of CSSStyleRule confused me. I just do instanceof check.
Can it return something other than CSSStyleRule? I am just curious if it is not a bug. Thanks

**Comment by phax** [comment]
Yes, media rules can contain other rules like namespace rules etc. So this is not a bug, but I could add extended APIs with typed rules

**Comment by dalibor-drgon** [comment]
I personally don't need it, but it may be useful for someone to add getAllStyleRules() to CSSMediaRule.
Anyway I just found out, that I need to use CascadingStyleSheet.getAllRules() and filter them manually for my application.
Many thanks for support.

**Comment by phax** [comment]
I extracted a common base class that does the handling for the top level rules in a type-safe way. This should resolve the issue also for the future. Thanks again for your input.
