### ISSUE TITLE
could not import com.helger.commons.*;

### ISSUE THREAD

**Issue by chowchow99** [phax/ph-css#40]
Hello Philip, 
         Thank you for offering such a great project.
          I copy paste the source file to my java project and some errors were found in 
          > com.helger.css.decl.visit.CSSVisitor
          > com.helger.css.CSSFilenameHelper
          > com.helger.css.CCSS
         because there is no  com.helger.commons.*  package in this  project.

**Comment by phax** [comment]
Please also download ph-commons in the appropriate version from https://github.com/phax/ph-commons/releases or from http://repo2.maven.org/maven2/com/helger/ph-commons/
Additionally SLF4J might be needed. hth

**Comment by chowchow99** [comment]
Thanks，it helps me alot.
