### ISSUE TITLE
How to get a simple style?

### ISSUE THREAD

**Issue by ControlAdad** [phax/ph-css#43]
Hi
I am a newbie in you library, I have **Style.css** as :
```
.qsign
{
    color:red;
}

```

I read a css using this :

        var cssString = Utils.readStringFromAssets(context, "Style.css")
        css=CSSReader.readFromString(cssString,ECSSVersion.CSS30)

Now how can I get color of **qsign** class?

**Comment by phax** [comment]
Hi. Assuming `css` is of type `CascadingStyleSheet`:
```java
// Get the first rule
CSSStyleRule styleRule = css.getStyleRuleAtIndex (0);
CSSDeclaration cssColor = styleRule.getDeclarationOfPropertyNameCaseInsensitive ("color");
// "expression" is the value "red"
System.out.println (cssColor.getExpression ().getAsCSSString (new CSSWriterSettings ()));
```
Note 1: I haven't tested it.
Note 2: I see that this API is creapy and I will create small improvements for v6.0.0
```java
// Get the first rule
CSSStyleRule styleRule = css.getStyleRuleAtIndex (0);
CSSDeclaration cssColor = styleRule.getDeclarationOfPropertyNameCaseInsensitive ("color");
// "expression" is the value "red"
System.out.println (cssColor.getExpressionCSSString ());
```
