### ISSUE TITLE
CSSURI with non-lower-case scheme not recognized as data uri

### ISSUE THREAD

**Issue by silmeth** [phax/ph-css#44]
As stated in [RFC 3986](https://tools.ietf.org/html/rfc3986#section-3.1):

> Although schemes are case-
>   insensitive, the canonical form is lowercase and documents that
>   specify schemes must do so with lowercase letters.  An implementation
>   should accept uppercase letters as equivalent to lowercase in scheme
>   names (e.g., allow "HTTP" as well as "http") for the sake of
>   robustness but should only produce lowercase scheme names for
>   consistency.

But `ph-css` version 5.0.4 does not treat non-lowercase URIs as data URIs, eg.:
```java
new CSSURI("DaTa:,someData").isDataURL()
```
returns `false` even though it should return `true`.

I believe that’s a minor bug.

Such URIs are not very common (and probably even less so in CSS files), yet when you try to handle all wild varieties of things that happen on the web in a fashion similar to web browser, this behaviour becomes an issue and a user of the library needs to manually check URI scheme.

**Comment by phax** [comment]
Fixed for v6.0.0 - thx for pointing that out!
