### ISSUE TITLE
AWT dependencies in ECSSColor and CSSColorHelper and Android usage of ph-css

### ISSUE THREAD

**Issue by battlepope** [phax/ph-css#46]
Hi Philip,
We are using ph-css in our Android-App.
Today I started implementing parsing of colors and discovered, that there are dependencies to AWT in bot ECSSColor and CSSColorHelper. However, there is no AWT support on Android that I know of. 
So sadly, I can't make use of those classes/ enums to determine what kind of Color it is, the CSS contains or get RGB values of named CSS colors.

The root of all evil lies in
`final float [] aHSL = CSSColorHelper.getRGBAsHSLValue (nRed, nGreen, nBlue);`
of ECSSColor's constructor. Is there a possibility or plan for you to ditch AWT dependencies, or move them somewhere else, so we don't have to have AWT in order to use ECSSColor?

**Comment by phax** [comment]
Okay, point taken. Let me see what I can do, and how "breaking" the changes are....

**Comment by battlepope** [comment]
Wow, that was fast :). Thanks alot!
When building for devices with Android version <7, we have to use version 4.1.6 of your library. Building for android >=7, we use the latest version (6.0.0), since JDK 1.8 support has improved a lot with later android versions.
I guess I know the answer- but I have to ask anyway :) :
Is it possible to get the fix on older versions of your lib, that were based on JDK 1.7, too?

**Comment by phax** [comment]
Okay so if I get it right you need version 5.1.0 and 6.1.0 without awt support. okay will do it...

**Comment by battlepope** [comment]
Hi,
thanks for your answer and your amazing support. Sorry if I didn't make my point clear.
For older versions of Android we need 4.1.6 of your library without AWT, since this version seems to be the last one you built with JDK 1.7. 
Android <7 does not support lambdas correctly. So 5.x of your lib is not compatible to our older devices. 4.1.6 runs fine.
So the best solution for us would be:
- 6.x without awt
- 4.x without awt

I would be amazing if you could make that possible.

**Comment by phax** [comment]
ph-css 4.2.0: http://repo2.maven.org/maven2/com/helger/ph-css/4.2.0/

**Comment by battlepope** [comment]
4.2.0 works like a charm on our ancient Android 4.4 devices :). Thanks a lot!

**Comment by phax** [comment]
Your welcome - I was struggeling a bit with JavaDoc setup in 6.1.0 but a release will come today

**Comment by phax** [comment]
And finally - ph-css 6.1.0: http://repo2.maven.org/maven2/com/helger/ph-css/6.1.0/
n-joy :D
