### ISSUE TITLE
Question: Does the Reader support CSS custom properties? 

### ISSUE THREAD

**Issue by michael-schaefer** [phax/ph-css#47]
Hi, 

I am looking for libraries that might help me convert CSS custom properties to plain CSS. Can you tell me if the Reader will handle CSS custom properties currently? And if so, it should be simple to then output the objects in plain CSS, yes? 

More info on CSS custom properties here: 

https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables

Thanks,

M

**Comment by phax** [comment]
Hi Michael,
sorry for the delay - Easter vacation. I will check whether it is supported to parse CSS variables (I remember I saw them before but can't recall).
What I'm sure is not contain: the evaluation of CSS variables.
hth

**Comment by phax** [comment]
Reading works - see test file in commit

**Comment by phax** [comment]
Please re-open if there is something left
