### ISSUE TITLE
Coding Styleguide link doesn't work

### ISSUE THREAD

**Issue by epabst** [phax/ph-css#52]
In the README, the link in "Please look at my personal Coding Styleguide for the naming conventions used in this project." doesn't work.

**Comment by phax** [comment]
Ooooops. It is https://github.com/phax/meta/blob/master/CodingStyleguide.md - will fix it ASAP :)

**Comment by phax** [comment]
Okay. I checked it and for me it works... Weird. Is your link different?

**Comment by epabst** [comment]
Your link works, but the one in the README doesn't work.  It has https://github.com/phax/meta/blob/master/CodeingStyleguide.md (has an extra e in Codeing).

**Comment by phax** [comment]
Found it. Thanks. I didn't recall that the link was contained twice (once at the top, once at the bottom).
