### ISSUE TITLE
NullPointerException in getAsCSSString

### ISSUE THREAD

**Issue by ronnyshapiro** [phax/ph-css#53]
Test : 

```
String css = "@font-face { font-family: 'NeutraText-Bold'; src: url(https://www.someFonts.com/NeutraText-Bold.otf); }";

        for (ICSSTopLevelRule icssTopLevelRule : CSSReader.readFromStringStream(css, ECSSVersion.LATEST).getAllRules()) {
            icssTopLevelRule.getAsCSSString();
        }
```

From my understanding this due to order of static field initialization in `CSSWriterSettings` in which `DEFAULT_SETTINGS` is created before the default has been set.

Workaround is to create `CSSWriterSettings` and `setNewLineMode` and pass it to `getAsCSSString`.

**Comment by phax** [comment]
Good catch - no idea how this could slip through....
