### ISSUE TITLE
How to determine CSSSelector type?

### ISSUE THREAD

**Issue by hendraanggrian** [phax/ph-css#56]
As written in javadoc, `CSSSelector` represents a single selector that may be an element type selector, class selector, or ID selector. Is there a way to know which one of those type my `CSSSelector` are?

Alternatively, is it possible to obtain `.` or `#` prefix when obtaining `selector.getMemberAtIndex(0)`?

**Comment by phax** [comment]
The members of a `CSSSelector` are instances of `ICSSSelectorMember`.
See the file I added to get an basic understanding of the API.
Does that answer your question?

**Comment by hendraanggrian** [comment]
Thanks for quick response, the added test is clear enough. Pardon my lack of understanding, I didn't notice the class or id prefix is not removed.

**Comment by phax** [comment]
Glad it helped :)
If you have more questions don't hesitate to ask...
