### ISSUE TITLE
Unrecoverable error on numeric class

### ISSUE THREAD

**Issue by nafg** [phax/ph-css#61]
Fomantic-UI 2.8.5+ has a numeric class name. See https://github.com/fomantic/Fomantic-UI/issues/1544.

It's invalid CSS, but does that matter? In any case it should at least be a recoverable error, it seems too bad to lose the rest of the file because of one poorly defined selector.

Thanks.

**Comment by phax** [comment]
Hi. Are you relying on the browser compliant parsing, or are you taking basically anything?
I could allow it in the parser and let it fail conditionally... What do you think?

**Comment by nafg** [comment]
I don't really care. It just code-generates something that makes it easier to specify classes in a Scala DSL. On the off chance of wanting to use that class it's not the end of the world if it isn't in the DSL.

Besides, there is now a PR in fomantic to fix it: https://github.com/fomantic/Fomantic-UI/pull/1546

So, just do whatever makes the most sense to you, as the maintainer of the codebase. I don't care if it skips it or not.

**Comment by phax** [comment]
If you enable the browser complaint mode (`.setBrowserCompliantMode (true)`) than it works for me - see the test case I created. hth
