### ISSUE TITLE
Classification problem?

### ISSUE THREAD

**Issue by Panthevm** [phax/ph-css#62]
Why `:nth-child(n)` `:nth-last-child(n)` `:nth-last-of-type(n)` `:nth-of-type(n)` is a CSSSelectorSimpleMember, not a CSSSelectorMemberFunctionLike?

**Comment by phax** [comment]
Because functions have "expressions" as children, whereas the `nth-*` selector can have non-expression content.

**Comment by Panthevm** [comment]
Thank you for your answer, Philip. It is strange that a function is a function only when it takes an expression. If we think in this context, then why `:lang(en)`, which takes not an expression, is a function?

**Comment by Panthevm** [comment]
Currently, all pseudo-classes containing `()` are defined as CSSSelectorMemberFunctionLike, except :not() and :nth-*()

**Comment by phax** [comment]
From a grammatical point of view, each "nth-*" pseudo selector can only have a limited subset (like `odd`, `even`, `+`, `-` and digits). And this is handled separately when converting it to a domain model.
The effort to change this would be quite high (change in grammar handling) and I am not sure it is worth it. Is it a big pain point for you?

**Comment by Panthevm** [comment]
The problem is small. I came across this when I needed to determine if a pseudo-class is used in a ruleset. For `CSSSelectorSimpleMember` this is solved by the usual equality, but because of `nth`, I have to take into account that `.getValue` from it will give the function  `":nth-child(<arg>)"`

I apologize in advance for my English. This is my first issue :)

Thanks

**Comment by phax** [comment]
Don't worry about your English - it's quite understandable.
I take the liberty to close this issue anyway, since it is a small issue for you and I don't want to make this change :)
Thank you.
