### ISSUE TITLE
:not Selector parsed incorrectly

### ISSUE THREAD

**Issue by rockwotj** [phax/ph-css#66]
I thought I was going crazy, but it seems that `:not` with multiple selectors do not get parsed correctly?

Input: `:not(FOO, .BAR)`
Output: `:not(FOO, FOO)`

Here's a screenshot of the debugger output in Intellij.
![image](https://user-images.githubusercontent.com/8669100/119528053-7ef0c200-bd46-11eb-9ef6-c2af313530b2.png)

**Comment by phax** [comment]
Thanks for pointing this out. It always took the first selector only :(
Will be fixed in 6.3.2 which is building atm

**Comment by rockwotj** [comment]
Thank you for the speedy turn around time!
