### ISSUE TITLE
Unable to add declarations where property contains "--" or "@"

### ISSUE THREAD

**Issue by nhubbard** [phax/ph-css#70]
Hi there! I'm writing a tool that automatically converts CSS files to use the [Tailwind](https://tailwindcss.com) framework. 

I've encountered two problems while using `ph-css` to do in-place modifications of `CSSStyleRule` classes.

1. Tailwind uses a special declaration of sorts, called [`@apply`](https://tailwindcss.com/docs/functions-and-directives#apply), which lists the classes Tailwind should compile down into a complete CSS file. Unfortunately, if I attempt to add a simple declaration with a property name of [`@apply`](https://tailwindcss.com/docs/functions-and-directives#apply), the declaration is silently dropped. For now, I've resorted to adding a `tailwind-apply` declaration and doing a find-and-replace operation before writing the output file to correct the issue.
2. Some of the Tailwind components, such as [Placeholder Opacity](https://tailwindcss.com/docs/placeholder-color), require the use of locally-scoped CSS variables in combination with a property declaration. When I attempt to add the variable declaration, which always contains `--` as part of its name, it is also silently dropped.

Here's an example of what I'm doing for issue 1:

```kotlin
// rule.allDeclarations is automatically provided by Kotlin, as an analog for rule.getAllDeclarations()
for (decl in rule.allDeclarations) {
    // [...] determine whether to add the declaration [...]
    // remove the old declaration
    rule.removeDeclaration(decl)
    // this is supposed to add the new declaration with the new Tailwind class
    // the result of this next line does not appear in the rule, unless I replace "@apply" with "tailwind-apply"
    rule.addDeclaration(CSSDeclaration("@apply", CSSExpression.createSimple(newTailwindClassName)))
}
```

Here's an example of what I'm doing for issue 2:

```kotlin
// Same situation as issue 1. When this line runs, no discernable action happens.
rule.addDeclaration(CSSDeclaration("--tw-placeholder-opacity", CSSExpression.createNumber(1)))
```

**Comment by phax** [comment]
ad 1.) Well, the problem is, that `@apply` translates to an `unknown rule` in the grammar. The '@' sign is simply not an allowed characters for identifiers. Due to the heavy use of the '@' sign in other places of the grammar, I don't know what the impact would be, if `@` would be added as an allowed character for identifiers. Maybe that could be a customization element handled outside the grammar (sthg like `allowAtInIdentifier:boolean` or so)

Regarding issue 2: there was a fix in a previous version that should resolve this. Please ensure you are using the latest version 6.3.4

**Comment by nhubbard** [comment]
Thanks for the fast reply! Since I already have a fix for issue 1 (using `tailwind-apply` and then replacing it before writing the file), that limitation isn't much of an issue.

For issue 2, I was already on that version, so I rewrote the portion of my code that added the variable, and it suddenly started working. Maybe I just made a mistake there.

**Comment by phax** [comment]
Okay cool. Happy coding :)
