### ISSUE TITLE
:lang with empty expression list parsed incorrectly

### ISSUE THREAD

**Issue by shagkur** [phax/ph-css#72]
An incorrectly empty lang function type pseudo class like:
```
:lang() {
	color: black;
}
```
is parsed incorrectly (should probably even dropped) to this:
`:lang( { color:black; }`

**Comment by phax** [comment]
Part of 6.4.1

**Comment by phax** [comment]
(I don't want to add specific rules to all pseudo classes, except where specific syntax requirements are provided)
