### ISSUE TITLE
:host and ::slotted pseudo class/element functions are parsed incorrectly (used in shadow DOM)

### ISSUE THREAD

**Issue by shagkur** [phax/ph-css#73]
Following pseudo class function is parsed incorrectly:
`:host(<simple_selector_sequence>)`

Following pseudo element function is paresed incorrectly:
`::slotted(<simple_selector_sequence>)`

**Comment by shagkur** [comment]
Here's my PR (proposal)
https://github.com/phax/ph-css/pull/74

**Comment by phax** [comment]
Will be part of 6.4.1
