### ISSUE TITLE
:host and ::slotted parsing sort of wrong

### ISSUE THREAD

**Issue by shagkur** [phax/ph-css#77]
This is a follow up issue to the recently merged PR. 
I figured that 
```
(<S>)*
( simpleSelectorSequence() )? 
```
is not correct. 
It should rather be
```
(<S>)*
( simpleSelectorSequence() (<S>)* )* 
```
 see: https://developer.mozilla.org/en-US/docs/Web/CSS/::slotted

Although i'm not quite sure about the trailing (<S>)* here. WDYT?

I'll file a PR soonish

**Comment by phax** [comment]
No need to PR - thx

**Comment by shagkur** [comment]
Sorry if i messed this up with my previous PR

**Comment by phax** [comment]
No worries - all good

**Comment by shagkur** [comment]
Thanks alot for your quick response on this :) Very appreciated :)
