### ISSUE TITLE
Scientific number notation not supported by parser

### ISSUE THREAD

**Issue by shagkur** [phax/ph-css#79]
Scientific numbers, like `1e-06`, are parsed incorrectly.
From quick glance into `ParserCSS30.jjt` the `DIMENSION` rule is commented out. Which, as of spec, seems to reflect the handling of scientific numbers.
Any reason why this is commented out?

In my current project i do not have any control over the incoming CSS (since it is "provided" by the browser and as such it can happen that very small floating values end up in this scientific notation)

**Comment by phax** [comment]
The `<DIMENSION>` rule was a try to simplify the grammar, but it caused issues - I can't recall which ones.
The extension point here is the internal <NUM> rule which misses support

**Comment by phax** [comment]
I extended it - my tests work. Please crosscheck if it works for you as well

**Comment by phax** [comment]
Okay, part of 6.4.3
