### ISSUE TITLE
*IDENT (<=IE6 hack) in style declaration block, drops all declarations after this one (in browser compliant mode)

### ISSUE THREAD

**Issue by shagkur** [phax/ph-css#84]
There're still CSS out there using/supporting this "hack". Dropping this specific declaration is perfectly fine, but unfortunately the rest after this declaration is also dropped (in browers compliant mode)

**Comment by phax** [comment]
In the PR you are throwin a PareseException in case of error. What is your goal? Just drop that particular property?

**Comment by shagkur** [comment]
> In the PR you are throwin a `ParseException` in case of error. What is your goal? Just drop that particular property?

Yeees. It should drop that particular property in browser compliant mode (which should be achieved by the catch clause in the `styleDeclaration()` rule then) otherwise it should throw thru the exception (and will/should then be catched in `styleDeclarationBlock()` rule). If i understood everything right.

And then it should, depending on the mode, result on what you described in the next post.

**Comment by phax** [comment]
Stupid one - please confirm. If so, I will release

**Comment by shagkur** [comment]
Sorry for answering late....
Work great. This is way better solution, especially regarding the error reporting.
Thanks alot for putting your time into this :)

**Comment by phax** [comment]
Part of 6.4.5 release that I will be creating now
