### ISSUE TITLE
Avoid subclassing "Error"

### ISSUE THREAD

**Issue by ChrisSpagnoli** [phax/ph-css#9]
com.helger.css.parser.TokenMgrError extends Error.  It would be better to extend Exception, or perhaps (if you do not want to avoid declaring it in the throws clause) RuntimeException.  The reason being that most developers will wrap a block of code with catch(Exception) to handle any issues within it, and an Error will not be caught (because Errors are generally unrecoverable anyway).  In our code, this resulted in the termination of the loop which was supposed to keep re-reading the CSS file when it changed (because an incorrect character in the CSS file caused a parse error).

A syntax error when parsing a CSS file is simply not in the same league as an "Error" (example Errors are OutOfMemoryError or a required Class file being missing).

Thank you.

References:
(1) http://www.javamex.com/tutorials/exceptions/exceptions_hierarchy.shtml
(2) http://docs.oracle.com/javase/7/docs/api/java/lang/Error.html

**Comment by phax** [comment]
Hi Chris!

Thanks for pointing that out. I usually tend to catch "Throwable" and that's why I didn't notice it.
The problem is only, that this is an automatically generated class from JavaCC and I need to dive into it, how to change it to Exception or RuntimeException.
I will come back to you, when I know more!

**Comment by phax** [comment]
Hi!

I found the following statement on https://javacc.java.net/doc/errorrecovery.html:

> The exception TokenMgrError is a subclass of Error, while the exception ParseException is a subclass of Exception. The reasoning here is that the token manager is never expected to throw an exception - you must be careful in defining your token specifications such that you cover all cases. Hence the suffix "Error" in TokenMgrError. You do not have to worry about this exception - if you have designed your tokens well, it should never get thrown. Whereas it is typical to attempt recovery from Parser errors - hence the name "ParseException". (Although if you still want to recover from token manager errors, you can do it - it's just that you are not forced to catch them.) 

Do you have potentially a stacktrace, how this occurred?

Thanks, Philip

**Comment by phax** [comment]
Anyway I changed the internal ParseUtils.validateIdentifier method to throw IllegalArgumentException instead of TokenMgrError. hth

**Comment by ChrisSpagnoli** [comment]
Philip,

As requested, a stack trace:
>  at com.helger.css.parser.ParserCSSCharsetDetectorTokenManager.getNextToken(ParserCSSCharsetDetectorTokenManager.java:695)
  at com.helger.css.parser.ParserCSSCharsetDetector.jj_ntk_f(ParserCSSCharsetDetector.java:182)
  at com.helger.css.parser.ParserCSSCharsetDetector.styleSheetCharset(ParserCSSCharsetDetector.java:16)
  at com.helger.css.reader.CSSReader.getCharsetDeclaredInCSS(CSSReader.java:1393)
  at com.helger.css.reader.CSSReader.readFromStream(CSSReader.java:1524)
  at com.helger.css.reader.CSSReader.readFromStream(CSSReader.java:1175)
  ...

The triggering CSS:
/*
*
That reproduces it - an incompletely formed comment.

And finally...
Awesome, throwing IllegalArgumentException  will be perfect!
Thank you, VERY much.
:)

**Comment by phax** [comment]
Thanks for pointing this out.
I think I fixed it both if the file starts with an invalid comment, as well as when it ends with an invalid comment. In both cases, the read result is "null".

You may check the Issue9Test.java file for a test :)

**Comment by ChrisSpagnoli** [comment]
Philip,
Most Awesome!  Thank you.

**Comment by phax** [comment]
So you need a release?

Am 27. März 2015 21:38:15 MEZ, schrieb ChrisSpagnoli <notifications@github.com>:
>Philip,
>Most Awesome!  Thank you.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/phax/ph-css/issues/9#issuecomment-87081701

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by ChrisSpagnoli** [comment]
Not just for this, we will get it in the next release, no worries.  And thank you for asking! :)
