### ISSUE TITLE
Can't parse Bulma 1.0

### ISSUE THREAD

**Issue by nafg** [phax/ph-css#97]
https://cdn.jsdelivr.net/npm/bulma@1.0.1/css/bulma.css fails with

`ERROR com.helger.css.handler.LoggingCSSParseExceptionCallback - Failed to parse CSS: [5368:29] Encountered text ' ' corresponding to token <S>. Was expecting one of: <NUMBER>, <EM>, <EX>, <FR>, <PX>, <CH>, <REM>, <VW>, <VH>, <VMIN>, <VMAX>, <DPI>, <DPCM>, <DPPX>, <LENGTH_CM>, <LENGTH_MM>, <LENGTH_Q>, <LENGTH_IN>, <LENGTH_PT>, <LENGTH_PC>, <ANGLE_DEG>, <ANGLE_RAD>, <ANGLE_GRAD>, <ANGLE_TURN>, <TIME_MS>, <TIME_S>, <FREQ_HZ>, <FREQ_KHZ>, <PERCENTAGE>`

**Comment by phax** [comment]
The fix for #101 and #88 seems to have resolve this issue as well. Will be fixed in 7.0.3
